translate FAQ part on surveys.yml
Devographics/locale-ko-KR pull request #17
Opened 2023-12-04 01:24 UTC by makepado

부족한 실력이지만 FAQ 파트를 번역해보았습니다.
열린 마음으로 오탈자 혹은 번역 개선 조언 부탁드립니다.

2023-12-04 12:21 UTC, gunhoflash requested changes
링크 유지를 위한 제안 드립니다!

2023-12-04 12:21 UTC, gunhoflash commented on surveys.yml
> +    t: 설문조사는 커뮤니티의 피드백을 바탕으로 설계되고 전문가들의 검토를 거칩니다. 자세한 내용은 여기에서 확인할 수 있습니다(https://dev.to/sachagreif/how-the-state-of-js-css-surveys-are-run-4lnb).
링크를 유지할 수 있으면 좋겠습니다.
```suggestion
    t: 설문조사는 커뮤니티의 피드백을 바탕으로 설계되고 전문가들의 검토를 거칩니다. [자세한 내용은 여기에서 확인할 수 있습니다](https://dev.to/sachagreif/how-the-state-of-js-css-surveys-are-run-4lnb).
```

2023-12-05 02:58 UTC, makepado commented
> 링크 유지를 위한 제안 드립니다!

미처 생각지 못한 부분 친절히 알려주셔서 감사합니다!

2023-12-05 02:58 UTC, makepado commented
> 최근 @Heunsig 님의 작업과 비슷한 항목이기에 내용과 형식이 통일되면 더 좋지 않을까 생각합니다. https://github.com/Devographics/locale-ko-KR/pull/14/files#diff-07918f10028cfdb03ce0ee9424839c0df529d8d0d3267acf0a662d57c30cd696R502-R554

잘 살펴봐주셔서 감사합니다, 해당 부분과 유사하게 다시 수정해봤습니다! :)

2023-12-05 11:51 UTC, Heunsig approved these changes
문제 없어보입니다 :)

2023-12-10 03:09 UTC, Heunsig commented
@makepado 번역에 큰 이상은 없는것 같은데 머지 진행해도 좋을 것 같습니다. 아니면 혹시 다른분의 리뷰를 계속 기다리고 계시는 걸까요?

2023-12-10 03:16 UTC, makepado commented
> @makepado 번역에 큰 이상은 없는것 같은데 머지 진행해도 좋을 것 같습니다. 아니면 혹시 다른분의 리뷰를 계속 기다리고 계시는 걸까요?

아 아닙니다 그럼 머지 진행하도록 하겠습니다!

2023-12-10 03:16 UTC, merged